test:
  client_id: ca_3nTTr9BZCUGQ9Cx4llmdACJ3NR8XKjt3
  secret_key: sk_test_jszcvwyjc5aC1mWSjDUBRqFt
  publishable_key: pk_test_NcdbxcuUjEJu2wMNX0LXv5Aa

development:
  client_id: ca_3nTTr9BZCUGQ9Cx4llmdACJ3NR8XKjt3
  secret_key: sk_test_jszcvwyjc5aC1mWSjDUBRqFt
  publishable_key: pk_test_NcdbxcuUjEJu2wMNX0LXv5Aa

production:
  client_id: ca_3nTT0PQ6y0yMXKYHUKwQNO8mo6R6Ne4J
  secret_key: sk_live_pbu275QWLmoTpkWQrOJYutAA
  publishable_key: pk_live_5D9QdmvkYUnP9kYn93uQ2ajB

